# name: NestJS CI/CD

# on:
#   pull_request:
#     branches: [ main, dev, uat ]

# jobs:

#   lint:
#     name: Call Test Job
#     uses: ./.github/workflows/lint.yml

#   build:
#     needs: lint
#     runs-on: ubuntu-latest

#     services:
#       postgres:
#         image: postgres:latest
#         env:
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: postgres
#           POSTGRES_DB: test_db
#         ports:
#           - 5432:5432
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5

#     steps:
#     - uses: actions/checkout@v3
    
#     - name: Setup Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '16'
        
#     - name: Install dependencies
#       run: npm ci

#     - name: Build
#       run: npm run build
      
#     - name: Run tests
#       run: npm test
#       env:
#         DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db

#   test:
#     needs: build
#     uses: ./.github/workflows/test.yml