# name: Deploy to Server

# on:
#   push:
#     branches:
#       - main

# jobs:
#   lint:
#     name: Call Test Job
#     uses: ./.github/workflows/lint.yml

#   build: 
#     needs: lint
#     name: Build on ubuntu
#     uses: ./.github/workflows/build.yml

#   test:
#     needs: build
#     name: Test on ubuntu
#     uses: ./.github/workflows/test.yml

#   deploy:
#     needs: test
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Deploy to server
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USERNAME }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           script: |
#             cd /path/to/your/app
#             git pull
#             npm install
#             npm run build
#             pm2 restart your-app-name