# name: Run Jest Tests

# on:
#   workflow_dispatch:
#   workflow_run:
#   workflow_call:

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
    
#     - name: Setup Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: 18

#     runs-on: ubuntu-latest

#     services:
#       postgres:
#         image: postgres:latest
#         env:
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: postgres
#           POSTGRES_DB: test_db
#         ports:
#           - 5432:5432
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5

#     steps:
#     - uses: actions/checkout@v3
    
#     - name: Setup Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '16'
        
#     - name: Install dependencies
#       run: npm ci

#     - name: Run tests
#       run: npm test
#       env:
#       APP_NAME: "Nest Monorepo"
#       APP_SECRET: "T9imckWWfLuVJC4tTac/B7T8IXljtegNKPfmvuVd0znAMIBkOkcjHLe1kSReQ7FKROjs+zrH8SeG+WKmM2qlHQ=="
#       APP_BACKEND_PORT: 8001
#       APP_CLIENT_PORT: 8002
#       APP_TIMEZONE: UTC
#       DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
#       ALLOWED_ORIGINS: "http://localhost:3001,http://localhost:3000"
#       ALLOWED_METHODS: "GET,POST,PUT,PATCH,DELETE"
#       ALLOWED_HEADERS: "Content-Type,Authorization"
#       ADMIN_FRONTEND_APP_URI: "http://localhost:3001"
#       CLIENT_FRONTEND_APP_URI: "http://localhost:3000"
