FROM node:22-alpine AS builder

WORKDIR /app
COPY package*.json ./
COPY uploads ./uploads
COPY mails ./mails
RUN npm install
COPY . .
RUN npm run build:client

FROM node:22-alpine AS runner

WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/uploads ./uploads
COPY --from=builder /app/mails ./mails

ENV PORT=8002
EXPOSE 8002
CMD ["npm", "run", "start:client:prod"]
