version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '8001:8001'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nest_db
      - NODE_ENV=production
      - PORT=8001
    depends_on:
      - db
    volumes:
      - uploads:/app/uploads
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - '8002:8002'
    environment:
      - NODE_ENV=production
      - PORT=8002
    volumes:
      - uploads:/app/uploads
    networks:
      - app-network

  db:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  uploads:
